### ISSUE TITLE
ConcurrentModificationException (AbstractFastMachine)

### ISSUE THREAD

**Issue by IAISI** [GuizhanCraft/FastMachines#24]
### Checklist

- [X] You are using official version downloaded from Blob Builds (https://blob.build/) or Guizhan Builds (<https://builds.guizhanss.com>)
- [X] You checked the checksum of the downloaded file, and confirmed that the file is complete
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

```
com.destroystokyo.paper.exception.ServerEventException: Could not pass event InventoryClickEvent to Slimefun v4.9-UNOFFICIAL
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:72)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3117)
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1458)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1435)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1358)
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1336)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1220)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at SlimefunFastMachines.jar//net.guizhanss.fastmachines.items.machines.abstracts.AbstractFastMachine.updateChoice(AbstractFastMachine.java:316)
	at SlimefunFastMachines.jar//net.guizhanss.fastmachines.items.machines.abstracts.AbstractFastMachine.lambda$updateMenu$5(AbstractFastMachine.java:303)
	at Slimefun4.jar//me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:56)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor176.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3117)
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58)
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220)
	... 2 more
```

Will try to update to latest build but looking at commits this probably wasn't fixed yet.

### Reproduction Steps

Not sure yet.

### Expected Behavior

Not sure yet.

### Server Software

Paper

### Minecraft version

1.20.4

### Slimefun version

> sf versions
[19:43:35 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-365 (MC: 1.20.4)
Slimefun 4.9-UNOFFICIAL
Metrics-Module #29
Java 17

Installed Addons: (16)
  Networks vDEV - 50 (git 3de3c9d6)
  Gastronomicon vDEV - 8 (git 76336191)
  ExtraTools v1.2
  FastMachines vBuild 13 (git 949e99d)
  SoundMuffler v1.0-SNAPSHOT
  SfChunkInfo vDEV - 8 (git b1b94abb)
  Bump vBuild 40 (git 811005e)
  DynaTech vMain - 6
  ExtraGear vDEV - 13 (git c62047e2)
  SlimefunLuckyBlocks vUNOFFICIAL
  ExoticGarden vUNOFFICIAL
  SlimeHUD vDEV - 11 (git b6dc2d53)
  InfinityExpansion vMODIFIED
  LiteXpansion vMODIFIED
  ExtraHeads vDEV - 25 (git 8c29f73a)
  FluffyMachines v1.0.0

### Plugin version

vBuild 13 (git 949e99d)

**Comment by IAISI** [comment]
Note: We're running latest Slimefun, the only thing we changed is to nerf enchant levels a bit.

**Comment by IAISI** [comment]
On latest SF and FastMachines this is still an issue.

**Comment by ybw0014** [comment]
should be fixed in build 21

**Comment by IAISI** [comment]
I think this is still an issue, sorta, but this time in net.guizhanss.fastmachines.items.machines.generic.FastMachineCache

exception related to net.guizhanss.fastmachines.items.machines.abstracts.AbstractFastMachine is not occuring anymore.

```
com.destroystokyo.paper.exception.ServerEventException: Could not pass event InventoryClickEvent to Slimefun v4.9-UNOFFICIAL
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:72)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3107)
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
	at net.minecraft.network.protocol.PlayerConnectionUtils.a(PlayerConnectionUtils.java:54)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1464)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:195)
	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1441)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1364)
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1342)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:1058)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:1055)
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:519)
	at java.base/java.util.LinkedHashMap.<init>(LinkedHashMap.java:480)
	at SlimefunFastMachines.jar//net.guizhanss.fastmachines.items.machines.generic.FastMachineCache.craft(FastMachineCache.java:196)
	at SlimefunFastMachines.jar//net.guizhanss.fastmachines.items.machines.generic.FastMachineCache.lambda$init$2(FastMachineCache.java:81)
	at Slimefun4.jar//me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:56)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor315.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3107)
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58)
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1464)
	at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:195)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1441)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1364)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1342)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
	... 2 more
```
